// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRouter struct {
	// where the message come from
	Source string `protobuf:"bytes,1,opt,name=Source,json=source,proto3" json:"Source,omitempty"`
	// where the message will send to
	Group string `protobuf:"bytes,2,opt,name=Group,json=group,proto3" json:"Group,omitempty"`
	// what's the operation on resource
	Operaion string `protobuf:"bytes,3,opt,name=Operaion,json=operaion,proto3" json:"Operaion,omitempty"`
	// what's the resource want to operate
	Resouce              string   `protobuf:"bytes,4,opt,name=Resouce,json=resouce,proto3" json:"Resouce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRouter) Reset()         { *m = MessageRouter{} }
func (m *MessageRouter) String() string { return proto.CompactTextString(m) }
func (*MessageRouter) ProtoMessage()    {}
func (*MessageRouter) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageRouter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRouter.Unmarshal(m, b)
}
func (m *MessageRouter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRouter.Marshal(b, m, deterministic)
}
func (m *MessageRouter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRouter.Merge(m, src)
}
func (m *MessageRouter) XXX_Size() int {
	return xxx_messageInfo_MessageRouter.Size(m)
}
func (m *MessageRouter) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRouter.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRouter proto.InternalMessageInfo

func (m *MessageRouter) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MessageRouter) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *MessageRouter) GetOperaion() string {
	if m != nil {
		return m.Operaion
	}
	return ""
}

func (m *MessageRouter) GetResouce() string {
	if m != nil {
		return m.Resouce
	}
	return ""
}

type MessageHeader struct {
	// the message uuid
	ID string `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	// the response message parent id must be same with the message received
	// please use NewRespByMessage to new response message
	ParentID string `protobuf:"bytes,2,opt,name=ParentID,json=parentID,proto3" json:"ParentID,omitempty"`
	// the time of creating
	Timestamp int64 `protobuf:"zigzag64,3,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	// the flag will be set in send sync
	Sync bool `protobuf:"varint,4,opt,name=Sync,json=sync,proto3" json:"Sync,omitempty"`
	// message type
	MessageType          string   `protobuf:"bytes,5,opt,name=MessageType,json=messageType,proto3" json:"MessageType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MessageHeader) GetParentID() string {
	if m != nil {
		return m.ParentID
	}
	return ""
}

func (m *MessageHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageHeader) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *MessageHeader) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

type Message struct {
	Header               *MessageHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Router               *MessageRouter `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"`
	Content              []byte         `protobuf:"bytes,3,opt,name=Content,json=content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetHeader() *MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Message) GetRouter() *MessageRouter {
	if m != nil {
		return m.Router
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageRouter)(nil), "message.MessageRouter")
	proto.RegisterType((*MessageHeader)(nil), "message.MessageHeader")
	proto.RegisterType((*Message)(nil), "message.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x71, 0x69, 0x93, 0xf4, 0xda, 0x22, 0x74, 0x42, 0x95, 0x55, 0x31, 0x54, 0x99, 0x3a,
	0x55, 0xa8, 0x4c, 0xcc, 0x54, 0x82, 0x0e, 0x08, 0xe4, 0xf6, 0x0b, 0x84, 0x70, 0x2a, 0x1d, 0x62,
	0x5b, 0xb6, 0x33, 0x74, 0xe6, 0x03, 0xf0, 0x95, 0x51, 0x2e, 0x0e, 0xff, 0xb7, 0xfc, 0x9e, 0x9f,
	0xee, 0x3d, 0xbd, 0xc0, 0xa4, 0x22, 0xef, 0x8b, 0x3d, 0x2d, 0xad, 0x33, 0xc1, 0x60, 0x1a, 0x31,
	0xf7, 0x30, 0x79, 0x68, 0x3f, 0x95, 0xa9, 0x03, 0x39, 0x9c, 0x42, 0xb2, 0x35, 0xb5, 0x2b, 0x49,
	0x8a, 0xb9, 0x58, 0x0c, 0x55, 0xe2, 0x99, 0xf0, 0x02, 0x06, 0x77, 0xce, 0xd4, 0x56, 0xf6, 0x58,
	0x1e, 0xec, 0x1b, 0xc0, 0x19, 0x64, 0x8f, 0x96, 0x5c, 0x71, 0x30, 0x5a, 0x9e, 0xf2, 0x43, 0x66,
	0x22, 0xa3, 0x84, 0x54, 0x91, 0x37, 0x75, 0x49, 0xb2, 0xcf, 0x4f, 0xa9, 0x6b, 0x31, 0x7f, 0x17,
	0x9f, 0xa9, 0xf7, 0x54, 0xbc, 0x90, 0xc3, 0x33, 0xe8, 0x6d, 0xd6, 0x31, 0xb1, 0x77, 0x58, 0x37,
	0x77, 0x9f, 0x0a, 0x47, 0x3a, 0x6c, 0xd6, 0x31, 0x30, 0xb3, 0x91, 0xf1, 0x12, 0x86, 0xbb, 0x43,
	0x45, 0x3e, 0x14, 0x95, 0xe5, 0x50, 0x54, 0xc3, 0xd0, 0x09, 0x88, 0xd0, 0xdf, 0x1e, 0x75, 0xc9,
	0x91, 0x99, 0xea, 0xfb, 0xa3, 0x2e, 0x71, 0x0e, 0xa3, 0x18, 0xb7, 0x3b, 0x5a, 0x92, 0x03, 0x3e,
	0x38, 0xaa, 0xbe, 0xa4, 0xfc, 0x4d, 0x40, 0x1a, 0x2d, 0xb8, 0x84, 0xe4, 0x95, 0x5b, 0x71, 0x9f,
	0xd1, 0x6a, 0xba, 0xec, 0xb6, 0xfb, 0xd1, 0x59, 0x45, 0x57, 0xe3, 0x77, 0xbc, 0x1d, 0x37, 0xfd,
	0xc7, 0xdf, 0x2e, 0xab, 0xa2, 0xab, 0xd9, 0xe5, 0xd6, 0xe8, 0x40, 0x3a, 0x70, 0xfb, 0xb1, 0x4a,
	0xcb, 0x16, 0x57, 0x1b, 0x18, 0xb3, 0xb7, 0x6b, 0x72, 0x03, 0x93, 0xef, 0xec, 0xf1, 0xfc, 0xf7,
	0xe9, 0xd9, 0x1f, 0x25, 0x3f, 0x59, 0x88, 0x2b, 0xf1, 0x9c, 0xf0, 0x7f, 0xbe, 0xfe, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0x91, 0xef, 0x22, 0xf8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteMessageClient is the client API for RouteMessage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteMessageClient interface {
	RouteMessages(ctx context.Context, opts ...grpc.CallOption) (RouteMessage_RouteMessagesClient, error)
}

type routeMessageClient struct {
	cc *grpc.ClientConn
}

func NewRouteMessageClient(cc *grpc.ClientConn) RouteMessageClient {
	return &routeMessageClient{cc}
}

func (c *routeMessageClient) RouteMessages(ctx context.Context, opts ...grpc.CallOption) (RouteMessage_RouteMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RouteMessage_serviceDesc.Streams[0], "/message.RouteMessage/RouteMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeMessageRouteMessagesClient{stream}
	return x, nil
}

type RouteMessage_RouteMessagesClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type routeMessageRouteMessagesClient struct {
	grpc.ClientStream
}

func (x *routeMessageRouteMessagesClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeMessageRouteMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouteMessageServer is the server API for RouteMessage service.
type RouteMessageServer interface {
	RouteMessages(RouteMessage_RouteMessagesServer) error
}

// UnimplementedRouteMessageServer can be embedded to have forward compatible implementations.
type UnimplementedRouteMessageServer struct {
}

func (*UnimplementedRouteMessageServer) RouteMessages(srv RouteMessage_RouteMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteMessages not implemented")
}

func RegisterRouteMessageServer(s *grpc.Server, srv RouteMessageServer) {
	s.RegisterService(&_RouteMessage_serviceDesc, srv)
}

func _RouteMessage_RouteMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteMessageServer).RouteMessages(&routeMessageRouteMessagesServer{stream})
}

type RouteMessage_RouteMessagesServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type routeMessageRouteMessagesServer struct {
	grpc.ServerStream
}

func (x *routeMessageRouteMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeMessageRouteMessagesServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RouteMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.RouteMessage",
	HandlerType: (*RouteMessageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RouteMessages",
			Handler:       _RouteMessage_RouteMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}
